### PR TITLE
fix memory leak in regions(cpu backend) & rgb2ycbcr(api level)

### LINKED ISSUE #1664: Memory Leak in CPU regions
`std::map` declared [here](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cpu/kernel/regions.hpp#L106-L109) is not clearing it's storage properly.

This was reported in google forums and the corresponding post can be found at [this URL](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/tldUree9bZE/BFeXtkVUBwAJ).

### LINKED ISSUE #1672: Memory leak in rgb2ycbcr
``` cpp
    size_t alloc_bytes, alloc_buffers, lock_bytes, lock_buffers;
        for (int i = 0; i < 5; i++) {
            af::array img = randu(100, 100, 3);
            array img2 = af::rgb2ycbcr(img);
            array y = img(span, span, 0);
            array cb = img(span, span, 1);
            array cr = img(span, span, 2);
            af::deviceMemInfo(&alloc_bytes, &alloc_buffers,  
                                 &lock_bytes, &lock_buffers);
            printf("%zu, %zu, %zu, %zu\n",
                   alloc_bytes, alloc_buffers,
                   lock_bytes, lock_buffers);
        }
```

### PR DESCRIPTION
**Pull request by 9prady9**
- [x] Fixes #1664 . Verified that the leak is not being reported in Valgrind anymore.
- [x] Fixes #1672 . Verified that the leak is not being reported in Valgrind anymore.

### CODE REVIEW

**Comment by 9prady9** [comment]
build arrayfire linux ci
build arrayfire osx opencl ci
build arrayfire windows opencl ci

**Comment by 9prady9** [comment]
build arrayfire linux cpu ci
build arrayfire osx cpu ci
build arrayfire windows cpu ci

**Comment by 9prady9** [comment]
build arrayfire linux ci

File: src/backend/cpu/kernel/regions.hpp [hunk 1]
```diff
@@ -178,6 +178,9 @@ void regions(Array<T> out, const Array<char> in, af_connectivity connectivity)
         }
     }
 
+    for (auto& mapElem: lmap)
+        delete mapElem.second;
```
Comment (9prady9) [inline src/backend/cpu/kernel/regions.hpp]: I thought about unique pointers, but then i thought why add another abstraction instead of just cleaning them off at the end since this object's definition and usage is local to that function. Will using unique pointers make it more efficient ?

Comment (umar456) [inline src/backend/cpu/kernel/regions.hpp]: unique ptrs aren't abstractions. They are there to make this type of thing from not happening again. You should almost never use raw pointers

**Comment by shehzan10** [comment]
build arrayfire windows cpu ci

**Comment by 9prady9** [comment]
build arrayfire windows cpu ci

File: src/api/c/ycbcr_rgb.cpp [hunk 2]
```diff
@@ -85,18 +84,18 @@ static af_array convert(const af_array& in, const af_ycc_std standard)
...
+    const Array<T>& input = getArray<T>(in);
+    std::vector<af_seq> indices(4, af_span);
+
+    indices[2] = {0, 0, 1};
+    Array<T> X = createSubArray(input, indices, false);
+
+    indices[2] = {1, 1, 1};
+    Array<T> Y = createSubArray(input, indices, false);
+
+    indices[2] = {2, 2, 1};
```
Comment (shehzan10) [inline src/api/c/ycbcr_rgb.cpp]: If you are making another commit in this PR, can you add a comment saying why you are only assigning to `indices[2]` in all the 3 cases. I think it would help code readability.

Comment (pavanky) [inline src/api/c/ycbcr_rgb.cpp]: @shehzan10 Because he is reading the three channels into 3 different arrays ?

@9prady9 Can you check if something like `createSubArray(input, {af_span, af_span, {1,1,1}}, false);` works.

Comment (9prady9) [inline src/api/c/ycbcr_rgb.cpp]: I have left comments before the [beginning of extraction](https://github.com/9prady9/arrayfire/blob/d1e61c2b133a9b5bfbdc2a80357095cd41b0523b/src/api/c/ycbcr_rgb.cpp#L85-L98) of channels. In any case, i don't have any other commits left in this PR.

Comment (shehzan10) [inline src/api/c/ycbcr_rgb.cpp]: I know why he is doing it, but it took me a bit to realize it. That's why I said "if you are making another commit", because its not that much of a priority. It just helps anyone in the future who is going to read it.

Comment (9prady9) [inline src/api/c/ycbcr_rgb.cpp]: @pavanky I checked by running the existing tests, why would we need copy's of original Array ? Just indexed Array's are sufficient right ?

Comment (9prady9) [inline src/api/c/ycbcr_rgb.cpp]: Is there a possibility that the meta-data may not be properly altered ?

Comment (pavanky) [inline src/api/c/ycbcr_rgb.cpp]: @9prady9 Check my comment again. I did not say anything about copy, I was wondering if array initializers work instead of using vectors.

**Comment by 9prady9** [comment]
That is the reason I asked for clarification. I didn't get what you were
concerned about. They seem to be working.

File: src/backend/cpu/kernel/regions.hpp [hunk 3]
```diff
@@ -98,78 +99,77 @@ static void setUnion(LabelNode<T>* x, LabelNode<T>* y)
...
-    T    *out_ptr = out.get();
+    const af::dim4 inDims = in.dims();
+    const char *inPtr  = in.get();
+    T *outPtr = out.get();
 
     // Map labels
-    typedef typename std::map<T, LabelNode<T>* > label_map_t;
-    typedef typename label_map_t::iterator label_map_iterator_t;
+    typedef typename std::unique_ptr< LabelNode<T> > UnqLabelPtr;
+    typedef typename std::map<T, UnqLabelPtr > LabelMap;
```
Comment (umar456) [inline src/backend/cpu/kernel/regions.hpp]: This is only used once. It is an unnecessary indirection but not a big deal. Your call

Also. Use the using keyword for type aliasing. They are easier to read and more powerful.
```
using LabelMap = typename std::map<T, UnqLabelPtr>;
```

File: src/backend/cpu/kernel/regions.hpp [hunk 4]
```diff
@@ -98,78 +99,77 @@ static void setUnion(LabelNode<T>* x, LabelNode<T>* y)
...
 
-    for (int j = 0; j < (int)in_dims[1]; j++) {
-        for (int i = 0; i < (int)in_dims[0]; i++) {
-            int idx = j * in_dims[0] + i;
-            if (in_ptr[idx] != 0) {
+    for (int j = 0; j < (int)inDims[1]; j++) {
+        for (int i = 0; i < (int)inDims[0]; i++) {
+            int idx = j * inDims[0] + i;
+            if (inPtr[idx] != 0) {
                 std::vector<T> l;
```
Comment (umar456) [inline src/backend/cpu/kernel/regions.hpp]: It would be better if this was a std::array instead of a std::vector. Since std::arrays are allocated on the stack, you don't get the penalty of calling malloc.

I know its not part of this PR. Perhaps in another issue.

File: src/backend/cpu/kernel/regions.hpp (hunk 3 above)
Comment (umar456) [inline src/backend/cpu/kernel/regions.hpp]: It's easier (for me) to read because it uses the assignment style to define the alias, not because it is shorter.
