### PR TITLE
Log dynamic lib loading failures from unified API

### LINKED ISSUE #2634: Enhance "Failed to load dynamic library" message
Hi
As today, if the unified backend failed to dyn load a backend, it messages out : 
"terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Failed to load dynamic library. :501):
Error in af_err unified::AFSymbolManager::call(const char*, CalleeArgs ...) [with CalleeArgs = {void**, unsigned int, const long long int*, af_dtype}]
In file src/api/unified/symbol_manager.hpp:60
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.
"

Would it be possible to add the name of the lib in the message : example: 
"  what():  ArrayFire Exception (Failed to load dynamic library libafcuda.so :501):"
?

### PR DESCRIPTION
**Pull request by 9prady9**
Help resolves #2634 

Added `AF_TRACE` commands when load library fails. Until now, only success is being reported in trace logs.

Cleaned up a unnecessary redirection in symbol_manage.cpp.

I tried to put trace command in `UNIFIED_ERROR_LOAD_LIB` macro but the dlerror call by that point is returning NULL because of earlier reads. I am still trying to figure out why/where this is happening.

### CODE REVIEW

**Comment by 9prady9** [comment]
Failure output
```
...
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /opt/arrayfire/lib/
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /opt/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/lib/
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/arrayfire/lib/
[unified][037674] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
Error in af_err unified::AFSymbolManager::call(const char*, CalleeArgs ...) [with CalleeArgs = {int*}]
In file src/api/unified/symbol_manager.hpp:60
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

../test/info.cpp:43: Failure
Expected equality of these values:
  AF_SUCCESS
    Which is: Success
  af_get_device_count(&nDevices)
    Which is: Failed to load dynamic library. 
[  FAILED  ] Info.All (1 ms)

```

**Comment by 9prady9** [comment]
Success
```
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /opt/arrayfire/lib//libafcpu.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/lib//libafcpu.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/arrayfire/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/arrayfire/lib//libafcpu.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: 
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:142 ] Found: libafopencl.so.3
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:149 ] Device Count: 2.
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: 
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: .
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load ./libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: ./src/backend/cuda
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load ./src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: ../src/backend/cuda
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load ../src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: src/backend/cuda
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: lib
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load lib/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: lib64
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load lib64/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: 
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /opt/arrayfire-3/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /opt/arrayfire-3/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /opt/arrayfire/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /opt/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: /usr/local/arrayfire/lib/
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load /usr/local/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][037734] [ ../src/api/unified/symbol_manager.cpp:195 ] AF_DEFAULT_BACKEND: opencl
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_get_device_count
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_get_device
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_set_device
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_info
ArrayFire v3.7.0 (OpenCL, 64-bit Linux, build c30d5455)
[0] NVIDIA: GeForce GTX 1060 3GB, 3011 MB
-1- AMD: Spectre, 2547 MB
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_randu
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_init
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_get_default_random_engine
[mem][037734] [ ../src/backend/opencl/memory.cpp:167 ] nativeAlloc: 4 KB 0x5647b69a26d0
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_get_backend_id
[unified][037734] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_release_array
ArrayFire v3.7.0 (OpenCL, 64-bit Linux, build c30d5455)
-0- NVIDIA: GeForce GTX 1060 3GB, 3011 MB
[1] AMD: Spectre, 2547 MB
[mem][037734] [ ../src/backend/opencl/memory.cpp:167 ] nativeAlloc: 4 KB 0x5647b6556540
[       OK ] Info.All (815 ms)
```

File: src/api/unified/symbol_manager.cpp [hunk 1]
```diff
@@ -133,10 +135,11 @@ LibHandle openDynLibrary(const af_backend bknd_idx) {
...
-        if ((retVal = loadLibrary(join_path(paths[i], bkndLibName).c_str()))) {
-            AF_TRACE("Found: {}", join_path(paths[i], bkndLibName));
+    for (size_t i = 0; i < extent<decltype(pathPrefixes)>::value; i++) {
+        AF_TRACE("Attempting: {}", pathPrefixes[i]);
+        if ((retVal = loadLibrary(
+                 join_path(pathPrefixes[i], bkndLibName).c_str()))) {
+            AF_TRACE("Found: {}", join_path(pathPrefixes[i], bkndLibName));
 
             func count_func =
                 (func)getFunctionPointer(retVal, "af_get_device_count");
```
Comment (umar456) [inline src/api/unified/symbol_manager.cpp]: Another failure condition is when the library is found but there are no devices associated with the library. This happens if you have an AMD GPU and you try to load the CUDA backend.

File: src/api/unified/symbol_manager.cpp [hunk 2]
```diff
@@ -133,10 +135,11 @@ LibHandle openDynLibrary(const af_backend bknd_idx) {
     typedef af_err (*func)(int*);
 
     LibHandle retVal = nullptr;
-    for (size_t i = 0; i < extent<decltype(paths)>::value; i++) {
-        AF_TRACE("Attempting: {}", paths[i]);
-        if ((retVal = loadLibrary(join_path(paths[i], bkndLibName).c_str()))) {
-            AF_TRACE("Found: {}", join_path(paths[i], bkndLibName));
+    for (size_t i = 0; i < extent<decltype(pathPrefixes)>::value; i++) {
+        AF_TRACE("Attempting: {}", pathPrefixes[i]);
```
Comment (umar456) [inline src/api/unified/symbol_manager.cpp]: Nice to have:

If the string is empty then change the message to:

Attempting: Default System Paths

Comment (9prady9) [reply src/api/unified/symbol_manager.cpp]: Sample output after change
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Info
[ RUN      ] Info.All
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: Default System Paths
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load libafcpu.so.3: cannot open shared object file: No such file or directory
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: .
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load ./libafcpu.so.3: cannot open shared object file: No such file or directory
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:139 ] Attempting: ./src/backend/cpu
[unified][002467] [ ../src/api/unified/symbol_manager.cpp:159 ] Failed to load ./src/backend/cpu/libafcpu.so.3: cannot open shared object file: No such file or directory
```

File: src/api/unified/symbol_manager.cpp (hunk 1 above)
Comment (9prady9) [reply src/api/unified/symbol_manager.cpp]: I don't understand do you want us to throw error in that case ? because we are already logging the device count in Line 149.

One logic where the library is still usable would be to cycle through each backend in the order of preference and switch to the first backend that we come across with at least one device. Even then, it wouldn't be error unless all backends has zero devices.

I will handle device selection logic in different PR, don't want to mix that with this logging related changes.
