### PR TITLE
Treat all JIT buffer parameters as non-linear parameters

### LINKED ISSUE #2436: CUDA_ERROR_INVALID_IMAGE error when running arrayfire on GPU
I am running into the following error:

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::string)
In file src/backend/cuda/jit.cpp:342
CU Error CUDA_ERROR_INVALID_IMAGE(200): device kernel image is invalid

In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:920

Running with AF_CUDA_MAX_JIT_LEN=10 makes the error go away. Also, running on cpu is fine.
Any ideas?

### PR DESCRIPTION
**Pull request by umar456**
This commit addresses very large kernels that were generated by the
JIT for smaller buffers. This was occuring because of how we were
estimating the JIT parameter sizes.

When targeting linear kernels we only pass the pointer to the kernel
instead of the entire dims and stride arrays. This generates smaller
parameter sets so we calculated kernels based on the pointer size
instead of the Param<T> size.

The issue occured when this kernel came in below the threshold for
evaluation but when it was used as a node to another operation, the
generated kernel became a non-linear kernel requiring us to pass
the Param<T> object for each buffer. This causes the size to go past
the limit of the parameters supported by CUDA and compilation fails.

This commit treats all kernels as non-linear kernel when calculating
the parameter sizes.

Fixes #2436 #2389

### CODE REVIEW

File: src/backend/cuda/Array.cpp [hunk 1]
```diff
@@ -249,30 +249,25 @@ Array<T> createNodeArray(const dim4 &dims, Node_ptr node) {
                 // some_buffer_size) BUT kernels who's kernel sizes come close
                 // to this value are not passing and cuModuleLoadDataEx is
                 // failing with CUDA_ERROR_INVALID_IMAGE(200). 35*sizeof(int)
-                // seems to be the magic number that passes all tests. I have no
-                // idea why this is the case.
+                // seems to be the magic number that passes all tests.
                 constexpr int max_param_size =
```
Comment (9prady9) [inline src/backend/cuda/Array.cpp]: make this also `size_t` to be consistent ?

File: test/jit.cpp [hunk 2]
```diff
@@ -421,9 +421,24 @@ TEST(JIT, ConstEval7) {
...
 
-    // I can't think of a good test for this.
     EXPECT_NO_THROW({
         eval(a, b, c, d, e, f, g);
         af::sync();
-      });
+    });
+}
+
+TEST(JIT, IncrementingBinary) {
```
Comment (9prady9) [inline test/jit.cpp]: Perhaps `VeryLargeTreeEvaluation` instead of `IncrementingBinary` makes more sense as the test name.

File: src/backend/cuda/Array.cpp [hunk 3]
```diff
@@ -249,30 +249,25 @@ Array<T> createNodeArray(const dim4 &dims, Node_ptr node) {
...
                     (4096 - (sizeof(Param<T>) + 35 * sizeof(uint)));
                 Node *n = node.get();
 
                 struct tree_info {
                     size_t buffer_size;
```
Comment (9prady9) [inline src/backend/cuda/Array.cpp]: This looks like is the size of all buffers under the current jit node. If that is correct, can we rename this appropriately.

**Comment by umar456** [comment]
Addressed all feedback
