### PR TITLE
Reduced build times and compilation fixes

### LINKED ISSUE #1500: Wrong MKL architecture path when building on Ubuntu 14.04 x86_64
When trying to build the library on Ubuntu 14.04, the following linker error occurs and the Intel MKL linker path in the argument list points to `-L/opt/intel/mkl/lib/ia32` rather than `-L/opt/intel/mkl/lib/intel64`:

```
/usr/bin/ld: skipping incompatible /opt/intel/mkl/lib/ia32/libmkl_rt.so when searching for -lmkl_rt
/usr/bin/ld: cannot find -lmkl_rt
```

Note that in CMake, the following related variables are set as follows:
```
CBLAS_mkl_rt_INCLUDE = /opt/intel/mkl/include
CBLAS_mkl_rt_LIBRARY = CBLAS_mkl_rt_LIBRARY-NOTFOUND
```
Setting the `CBLAS_mkl_rt_LIBRARY` path manually to `/opt/intel/mkl/lib/intel64/libmkl_rt.so` results in the warning:
```
 CMake Warning at src/backend/cpu/CMakeLists.txt:199 (ADD_LIBRARY):
   Cannot generate a safe linker search path for target afcpu because there is
   a cycle in the constraint graph:

     dir 0 is [/opt/intel/mkl/lib/intel64]
       dir 1 must precede it due to link library [libmkl_rt.so]
     dir 1 is [/opt/intel/mkl/lib/ia32]
       dir 0 must precede it due to link library [libmkl_rt.so]

   Some of these libraries may not be found correctly.
```

- CMake 3.3.1

### LINKED ISSUE #1514: Could not find FFTW3 at the configuration stage with Intel MKL used for the CPU backend
Hello there,

I've ran into a problem configuring Arrayfire's CPU backend to use Intel's MKL, and here is the output from CMake:

```
CMake Warning at CMakeLists.txt:92 (MESSAGE):
  Building With NONFREE ON requires the following patents


CMake Warning at CMakeLists.txt:102 (MESSAGE):
  Building with SIFT requires the following patents


Method and apparatus for identifying scale invariant featuresin an image and use of same for locating an object in an image," DavidG. Lowe, US Patent 6,711,293 (March 23, 2004). Provisional applicationfiled March 8, 1999. Asignee: The University of British Columbia. Forfurther details, contact David Lowe (lowe@cs.ubc.ca) or theUniversity-Industry Liaison Office of the University of BritishColumbia.
Checking for module 'cblas'
  No package 'cblas' found
Checking for [mkl_rt]
Includes found
CBLAS Symbols FOUND
CBLAS library found
CPU Backend Using MKL RT
CMake Error at /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FFTW (missing: FFTW_INCLUDES FFTW_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindFFTW.cmake:110 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/backend/cpu/CMakeLists.txt:58 (FIND_PACKAGE)


Configuring incomplete, errors occurred!
See also "/home/lin/source.build/GPGPU/arrayfire/build/CMakeFiles/CMakeOutput.log".
See also "/home/lin/source.build/GPGPU/arrayfire/build/CMakeFiles/CMakeError.log".
```

And attached below are the CMake logs (secret gists)

1. [CMakeOutput.log](https://gist.github.com/Brainiarc7/f566d5b8bfc159c1f0fa3bf4707f76c2)
2. [CMakeError.log](https://gist.github.com/Brainiarc7/d1f8b27098bef2831122dc09c4da6d95)

Platform used: Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1514
- Fixes #1500

[skip arrayfire ci]

### CODE REVIEW

**Comment by pavanky** [comment]
@shehzan10 I think this should PR should build on the Tegra K1. Can you give it a shot ?

**Comment by shehzan10** [comment]
build arrayfire tegrak1 ci
build arrayfire tegrax1 ci

**Comment by shehzan10** [comment]
Compilation looks good. Failures in tests. (Click details in PR status)

**Comment by shehzan10** [comment]
build arrayfire linux ci

File: src/api/c/scan.cpp [hunk 1]
```diff
@@ -186,10 +186,10 @@ af_err af_scan_by_key(af_array *out, const af_array key, const af_array in, cons
         case s32:  res = scan_op<int    , int    >(key, in, dim, op, inclusive_scan); break;
         case u64:  res = scan_op<uintl  , uintl  >(key, in, dim, op, inclusive_scan); break;
         case s64:  res = scan_op<intl   , intl   >(key, in, dim, op, inclusive_scan); break;
-        case u16:  res = scan_op<ushort , uint   >(key, in, dim, op, inclusive_scan); break;
-        case s16:  res = scan_op<short  , int    >(key, in, dim, op, inclusive_scan); break;
-        case u8:   res = scan_op<uchar  , uint   >(key, in, dim, op, inclusive_scan); break;
-        case b8:   res = scan_op<char   , uint   >(key, in, dim, op, inclusive_scan); break;
+        case u16:  res = scan_op<uint   , uint   >(key, in, dim, op, inclusive_scan); break;
```
Comment (umar456) [inline src/api/c/scan.cpp]: I think it would be better to error out for these cases and make the user perform the cast themselves. That way no one is surprised.

File: src/backend/cpu/scan_by_key.cpp [hunk 2]
```diff
@@ -20,40 +20,30 @@ using af::dim4;
...
-        }
-    }
-
     template<af_op_t op, typename Ti, typename Tk, typename To>
     Array<To> scan(const Array<Tk>& key, const Array<Ti>& in, const int dim, bool inclusive_scan)
     {
         dim4 dims     = in.dims();
         Array<To> out = createEmptyArray<To>(dims);
-        in.eval();
+        kernel::scan_dim_by_key<op, Ti, Tk, To, 1> func1(inclusive_scan);
```
Comment (umar456) [inline src/backend/cpu/scan_by_key.cpp]: vector<void(...)> func.push_back(...)?

File: src/backend/cuda/kernel/thrust_sort_by_key.hpp [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+#include <Param.hpp>
+namespace cuda
+{
+    namespace kernel
+    {
+        ///////////////////////////////////////////////////////////////////////////
+        // Wrapper functions
+        ///////////////////////////////////////////////////////////////////////////
+        template<typename Tk, typename Tv>
+        void thrustSortByKey(Tk *keyPtr, Tv *valPtr, int elements, bool isAscending);
```
Comment (umar456) [inline src/backend/cuda/kernel/thrust_sort_by_key.hpp]: very nice!

File: src/api/c/scan.cpp (hunk 1 above)
Comment (shehzan10) [inline src/api/c/scan.cpp]: We would be breaking behavior/API by doing that.

Comment (pavanky) [inline src/api/c/scan.cpp]: @umar456 We are not changing the output type. We are creating a temporary buffer from the input. I think that is fine.

@shehzan10 this is a new function, if we ever break behavior / API this is the time to do it.

Comment (shehzan10) [inline src/api/c/scan.cpp]: Ah my bad. I thought this was the old scan.
