### PR TITLE
Use correct reduce op type for boolean product

### LINKED ISSUE #2543: Product of b8 uses sum
It seems taking the product of a bit vector (`b8` array) is summing the elements. To reproduce:

```c
void test_bool () {
  bool data[5] = { 1,1,1,1,1 };                      
  dim_t * dims = malloc(sizeof(dim_t) * 4);
  dims[0] = 5;                                               
  dims[1] = 1;                                               
  dims[2] = 1;                                               
  dims[3] = 1;                                               
  af_array arrin;                                            
  af_create_array(&arrin, &data, 4, dims, b8);
  af_print_array(arrin);                                      
  af_array arrout;                                              
  af_product(&arrout, arrin, 0);                        
  printf("printing output array\n");                  
  af_print_array(arrout);                                   
} 
```
Expected:
```
printing output array
No Name Array
[1 1 1 1]
         1
```
Actual:
```
printing output array
No Name Array
[1 1 1 1]
         5 
```

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #2543

### CODE REVIEW

File: test/reduce.cpp [hunk 1]
```diff
@@ -685,3 +685,22 @@ TEST(Reduce, AllSmallIndexed) {
     array b       = a(seq(len / 2), span);
     ASSERT_EQ(max<float>(b), len / 2 - 1);
 }
+
+TEST(ProductAll, BoolIn_ISSUE2543_All_Ones) {
+    ASSERT_EQ(true, product<int>(constant(1, 5, 5, b8)) > 0);
```
Comment (umar456) [inline test/reduce.cpp]: Shouldn't product return char?

Wouldn't the Result be one? In that case use

```

```
```suggestion
    ASSERT_EQ(1, product<char>(constant(1, 5, 5, b8));
```
