### PR TITLE
Fix Clang warnings

### LINKED ISSUE #1206: Fix compiler warnings thrown by Clang
Look at http://ci.arrayfire.org/job/arrayfire-osx/job/pr-build/243/consoleFull for a sample build log for clang.

### PR DESCRIPTION
**Pull request by shehzan10**
[skip ci]
* Using std::abs instead of abs in tests, examples
* Other minor fixes in tests
* Proper warning push pop for clang

Fixes #1206

Some warnings this fixes:
```
In file included from /var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/kernel/homography.hpp:16:
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/kernel/ireduce.hpp:285:19: warning: unused function 'cabs' [-Wunused-function]
    static double cabs(const cfloat in) { return (double)abs(in); }
                  ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/kernel/ireduce.hpp:286:19: warning: unused function 'cabs' [-Wunused-function]
    static double cabs(const cdouble in) { return (double)abs(in); }

--------------
In file included from /var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.cpp:10:
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:39:12: warning: unused function 'max' [-Wunused-function]
    cfloat max<cfloat>(cfloat lhs, cfloat rhs)
           ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:45:13: warning: unused function 'max' [-Wunused-function]
    cdouble max<cdouble>(cdouble lhs, cdouble rhs)
            ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:51:12: warning: unused function 'min' [-Wunused-function]
    cfloat min<cfloat>(cfloat lhs, cfloat rhs)
           ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:57:13: warning: unused function 'min' [-Wunused-function]
    cdouble min<cdouble>(cdouble lhs, cdouble rhs)
            ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:69:13: warning: unused function 'scalar' [-Wunused-function]
    cfloat  scalar<cfloat >(double val)
            ^
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/math.hpp:78:13: warning: unused function 'scalar' [-Wunused-function]
    cdouble scalar<cdouble >(double val)
------------------

In file included from /var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/orb.cpp:17:
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/kernel/orb.hpp:33:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
----------------------

In file included from /var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/orb.cpp:17:
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/src/backend/opencl/kernel/orb.hpp:33:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
--------------------

/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/examples/image_processing/filters.cpp:230:44: warning: implicit conversion from 'double' to 'int' changes value from 0.8 to 0 [-Wliteral-conversion]
        array gb = gaussianblur(hrl, 3, 3, 0.8);
                   ~~~~~~~~~~~~            ^~~
1 warning generated.
/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/examples/image_processing/filters.cpp:230:44: warning: implicit conversion from 'double' to 'int' changes value from 0.8 to 0 [-Wliteral-conversion]
        array gb = gaussianblur(hrl, 3, 3, 0.8);
--------------------

/var/lib/jenkins-slave/workspace/arrayfire-osx/pr-build/examples/image_processing/brain_segmentation.cpp:26:13: warning: unused variable 'h_lp_kernel' [-Wunused-const-variable]
const float h_lp_kernel[] = { -0.5f, -1.0f, -0.5f,
```

### CODE REVIEW

**Comment by umar456** [comment]
Can you squash your commits?

File: src/backend/opencl/kernel/orb.hpp [hunk 1]
```diff
@@ -29,8 +29,24 @@ using cl::LocalSpaceArg;
 using cl::NDRange;
 using std::vector;
 
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
+#if defined(__clang__)
```
Comment (umar456) [inline src/backend/opencl/kernel/orb.hpp]: Clang will accept GCC pragmas but not the other way around. You should remove the clang pragmas.

Comment (shehzan10) [inline src/backend/opencl/kernel/orb.hpp]: Clang uses sometimes-uninitialized and not maybe-uninitialized. That's the warning thrown by clang as well. [link](http://fuckingclangwarnings.com/)

Comment (umar456) [inline src/backend/opencl/kernel/orb.hpp]: Ahh I see.

**Comment by pavanky** [comment]
I agree with @umar456 Squash all the commits for this into one.

**Comment by shehzan10** [comment]
squashed
