### PR TITLE
Quick Fix for issues arising with step size in sequences > 1

### LINKED ISSUE #1845: Bug in indexing after reorder
The following code will cause the opencl backend to crash:
```c++
#include <iostream>
#include <arrayfire.h>

using namespace std;
using namespace af;
int main()
{
    setBackend(AF_BACKEND_OPENCL);

    array a = array(1,512,1);
    array b = reorder(a,0,2,1);
    // array c = reorder(b(0,0,0),2,1,0);
    array d = reorder(b(0,0,span),2,1,0);
}

```
After this, all future calls to reorder will fail.

512 is the smallest number for which this occurs.
The bug only occurs when using span on the large dimension of b. 

However, the if you access some other parts of b first, the code will not crash. For example, if you uncomment the commented line, this code will run as expected. 

The reported error is:

```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
OpenCL Error (-36): Invalid Command Queue when calling clFinish
In function af::array af::reorder(const af::array&, unsigned int, unsigned int, unsigned int, unsigned int)
In file src/api/cpp/data.cpp:253
Aborted

```

### LINKED ISSUE #1846: Bug in Indexing an already indexed array
The following code should print all 1s, but it doesn't.

```
#include <iostream>
#include <arrayfire.h>

using namespace std;
using namespace af;
int main()
{
    af::info();
    af::array a = af::randu(3, 12);
    af::array b = a(span, af::seq(0, af::end, 2));
    af::array c = b(span, af::seq(0, af::end, 3));
    af::array d = a(span, af::seq(0, af::end, 6));
    af_print(c == d);
    return 1;
}
```

Related to #1845

### PR DESCRIPTION
**Pull request by pavanky**
- Added relevant tests
- Updated release notes

- Fixes #1846 
- Fixes #1845

### CODE REVIEW

File: test/index.cpp [hunk 1]
```diff
@@ -1536,3 +1536,22 @@ TEST(Index, ISSUE_1101_MODDIMS)
...
+{
+    using namespace af;
+    af::array a = af::randu(3, 12);
+    af::array b = a(span, af::seq(0, af::end, 2));
+    af::array c = b(span, af::seq(0, af::end, 3));
+    af::array d = a(span, af::seq(0, af::end, 6));
+    ASSERT_EQ(af::allTrue<bool>(c == d), true);
+}
+
+TEST(Index, ISSUE_184_Index_Step_reorder)
```
Comment (umar456) [inline test/index.cpp]: ISSUE_1845_Index_Step_reorder

File: src/backend/opencl/Array.cpp [hunk 2]
```diff
@@ -268,14 +268,21 @@ namespace opencl
         parent.eval();
 
         dim4 dDims = parent.getDataDims();
+        dim4 dStrides = calcStrides(dDims);
+        dim4 parent_strides = parent.strides();
+
+        if (dStrides != parent_strides) {
+            const Array<T> &parentCopy = copyArray(parent);
```
Comment (umar456) [inline src/backend/opencl/Array.cpp]: copyArray returns an Array<T> by value. I would just make this a value Array<T> rather than a reference array. The createSubArray function should increase the reference count anyway. It would be a good idea to check.

File: test/index.cpp [hunk 3]
```diff
@@ -1536,3 +1536,22 @@ TEST(Index, ISSUE_1101_MODDIMS)
...
 }
+
+TEST(Index, ISSUE_1846_Index_Step_Cascade)
+{
+    using namespace af;
+    af::array a = af::randu(3, 12);
+    af::array b = a(span, af::seq(0, af::end, 2));
+    af::array c = b(span, af::seq(0, af::end, 3));
+    af::array d = a(span, af::seq(0, af::end, 6));
+    ASSERT_EQ(af::allTrue<bool>(c == d), true);
```
Comment (umar456) [inline test/index.cpp]: `EXPECT_TRUE(af::allTrue<bool>(c == d));`

File: test/index.cpp [hunk 4]
```diff
@@ -1536,3 +1536,22 @@ TEST(Index, ISSUE_1101_MODDIMS)
...
+}
+
+TEST(Index, ISSUE_184_Index_Step_reorder)
+{
+    using namespace af;
+    array a = af::randu(1,8,1);
+    array b = reorder(a,0,2,1);
+    array d = reorder(b(0,0,span),2,1,0);
+    ASSERT_EQ(af::allTrue<bool>(a.T() == d), true);
```
Comment (umar456) [inline test/index.cpp]: `EXPECT_TRUE(af::allTrue<bool>(a.T() == d));`

File: test/index.cpp [hunk 5]
```diff
@@ -1536,3 +1536,22 @@ TEST(Index, ISSUE_1101_MODDIMS)
         ASSERT_EQ(ha[i + st], hc[i]);
     }
 }
+
+TEST(Index, ISSUE_1846_Index_Step_Cascade)
+{
+    using namespace af;
+    af::array a = af::randu(3, 12);
+    af::array b = a(span, af::seq(0, af::end, 2));
```
Comment (umar456) [inline test/index.cpp]: af:: is unnecessary.
