### PR TITLE
Fix non-mkl & non-batch blas upstream call arguments

### LINKED ISSUE #2394: CPU Only backend built fail
Hi, there, I tried to build CPU only backend ("cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CUDA=OFF -DAF_BUILD_OPENCL=OFF
")

When issue "make -j4" I encountered following errors:

/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:243:31: error: cannot convert ‘const std::complex<float>*’ to ‘cpu::cptr_type<std::complex<float> > {aka const float*}’ in argument passing
                 gemv_func<T>()(CblasColMajor, lOpts, lDims[0], lDims[1], alpha,
                               ^
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:247:31: error: cannot convert ‘const std::complex<float>*’ to ‘cpu::cptr_type<std::complex<float> > {aka const float*}’ in argument passing
                 gemm_func<T>()(CblasColMajor, lOpts, rOpts, M, N, K, alpha,
                               ^
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp: In instantiation of ‘cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop)::<lambda(cpu::Param<T>, cpu::CParam<T>, cpu::CParam<T>)> [with T = std::complex<double>]’:
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:247:67:   required from ‘struct cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<double>]::<lambda(class cpu::Param<std::complex<double> >, class cpu::CParam<std::complex<double> >, class cpu::CParam<std::complex<double> >)>’
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:304:5:   required from ‘cpu::Array<T> cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<double>]’
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:344:1:   required from here
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:243:31: error: cannot convert ‘const std::complex<double>*’ to ‘cpu::cptr_type<std::complex<double> > {aka const double*}’ in argument passing
                 gemv_func<T>()(CblasColMajor, lOpts, lDims[0], lDims[1], alpha,
                               ^
/home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:247:31: error: cannot convert ‘const std::complex<double>*’ to ‘cpu::cptr_type<std::complex<double> > {aka const double*}’ in argument passing
                 gemm_func<T>()(CblasColMajor, lOpts, rOpts, M, N, K, alpha,
                               ^
In file included from /home/michael/fb/arrayfire/src/backend/cpu/platform.hpp:13:0,
                 from /home/michael/fb/arrayfire/src/backend/cpu/Array.hpp:16,
                 from /home/michael/fb/arrayfire/src/backend/cpu/blas.hpp:10,
                 from /home/michael/fb/arrayfire/src/backend/cpu/blas.cpp:10:
/home/michael/fb/arrayfire/src/backend/cpu/queue.hpp:59:10: error: ‘void cpu::queue::enqueue(F, Args ...) [with F = cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<float>]::<lambda(cpu::Param<std::complex<float> >, cpu::CParam<std::complex<float> >, cpu::CParam<std::complex<float> >)>; Args = {cpu::Array<std::complex<float> >, cpu::Array<std::complex<float> >, cpu::Array<std::complex<float> >}]’, declared using local type ‘cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<float>]::<lambda(cpu::Param<std::complex<float> >, cpu::CParam<std::complex<float> >, cpu::CParam<std::complex<float> >)>’, is used but never defined [-fpermissive]
     void enqueue(const F func, Args... args) {
          ^
/home/michael/fb/arrayfire/src/backend/cpu/queue.hpp:59:10: error: ‘void cpu::queue::enqueue(F, Args ...) [with F = cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<double>]::<lambda(cpu::Param<std::complex<double> >, cpu::CParam<std::complex<double> >, cpu::CParam<std::complex<double> >)>; Args = {cpu::Array<std::complex<double> >, cpu::Array<std::complex<double> >, cpu::Array<std::complex<double> >}]’, declared using local type ‘cpu::matmul(const cpu::Array<T>&, const cpu::Array<T>&, af_mat_prop, af_mat_prop) [with T = std::complex<double>]::<lambda(cpu::Param<std::complex<double> >, cpu::CParam<std::complex<double> >, cpu::CParam<std::complex<double> >)>’, is used but never defined [-fpermissive]

### PR DESCRIPTION
**Pull request by 9prady9**
Resolves #2394

### CODE REVIEW

File: src/backend/cpu/blas.cpp [hunk 1]
```diff
@@ -241,12 +241,16 @@ Array<T> matmul(const Array<T> &lhs, const Array<T> &rhs, af_mat_prop optLhs,
                 dim_t incr =
                     (optRhs == AF_MAT_NONE) ? rStrides[0] : rStrides[1];
                 gemv_func<T>()(CblasColMajor, lOpts, lDims[0], lDims[1], alpha,
-                               left.get(), lStrides[1], right.get(), incr, beta,
-                               output.get(), 1);
+                               reinterpret_cast<CBT*>(left.get()), lStrides[1],
```
Comment (umar456) [inline src/backend/cpu/blas.cpp]: use static_cast
