### PR TITLE
Corrected af_random_engine_set_type

### LINKED ISSUE #1715: Setting default random engine to Mersenne gives a segmentation fault
Code to reproduce

```
        af::setDefaultRandomEngineType(AF_RANDOM_ENGINE_PHILOX);
        array A = randu(5,3, f32);
        af_print(A);
```

This does not happen when using a user created random engine.

### PR DESCRIPTION
**Pull request by kaatish**
- Fixes #1715
-----------------
- Correct usage of getRandomEngine
- Remove redundant release of Mersenne arrays
- Added test for setDefaultRandomEngine

### CODE REVIEW

**Comment by pavanky** [comment]
build arrayfire ci

File: src/api/c/random.cpp [hunk 1]
```diff
@@ -179,29 +179,26 @@ af_err af_random_engine_set_type(af_random_engine *engine, const af_random_engin
...
+                AF_CHECK(af_release_array(e->sh2));
+                AF_CHECK(af_release_array(e->recursion_table));
+                AF_CHECK(af_release_array(e->temper_table));
+                AF_CHECK(af_release_array(e->state));
             }
-            e.type = rtype;
+            e->type = rtype;
         }
     } CATCHALL;
     return AF_SUCCESS;
```
Comment (pavanky) [inline src/api/c/random.cpp]: What's the logic for handling when the requested type is not mersenne twister?

Comment (kaatish) [inline src/api/c/random.cpp]: The arrays being handled in this section are specific to Mersenne Twister and are not needed otherwise.
