### PR TITLE
Graphics fixes

### LINKED ISSUE #1244: Correct af::Window default constructors behaviour
Currently, the following code stub, doesn't do anything which needs to resolved appropriately.

```c++
af::Window foo;
af::Window bar(foo);
```

### PR DESCRIPTION
**Pull request by 9prady9**
- Fixes #1244

### CODE REVIEW

File: include/af/graphics.h [hunk 1]
```diff
@@ -39,10 +64,15 @@ class AFAPI Window {
          * cell in the grid is being rendered currently */
         int _r;
         int _c;
-        ColorMap _cmap;
+        ColorMap        _cmap;
+        af_plot_limits  _range;
+        af_color        _color;
```
Comment (pavanky) [inline include/af/graphics.h]: Now this will definitely break API.

File: include/af/graphics.h [hunk 2]
```diff
@@ -43,6 +45,9 @@ class AFAPI Window {
 
         void initWindow(const int width, const int height, const char* const title);
 
+        Window(const Window&);                 // Prevent copy-construction
```
Comment (pavanky) [inline include/af/graphics.h]: Pradeep this may cause missing symbol errors I think. Don't we need to have " {} "  as well?

@umar456 I am not entirely sure about this can you take a look ?

Comment (9prady9) [inline include/af/graphics.h]: Worked on my Arch but not sure if it will on Windows.

**Comment by 9prady9** [comment]
build arrayfire ci

**Comment by 9prady9** [comment]
@pavanky All jenkins builds passed without any issues.
