### PR TITLE
Fix morphology fns to handle even size kernels

### LINKED ISSUE #1940: System Image viewer showing black image for float tiff images saved by saveImageNative
arrayfire v.3.5.1 Release
```
af::setBackend(AF_BACKEND_CUDA);
//af::setBackend(AF_BACKEND_CPU);
array img = loadimage("Test1_000000.tif",false);
array mask = constant(1.f, 19, 19);
int maxI = (int)max<unsigned char>(img);
int minI = (int)min<unsigned char>(img);
img = (img -minI)/(maxI-minI);
img = 254 -img;
img = (erode(img, mask));
img = 254 -img;

img = erode(img, mask);	
saveImageNative("outt.tif", img);

```
Original:
test1_000000

AF_BACKEND_CPU
outt_cpu
AF_BACKEND_CUDA (8.0)
outt_cuda

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #1940 

Also, reduces the compilation time by reducing morph template instantiations.

### CODE REVIEW

**Comment by pavanky** [comment]
Add tests.

**Comment by 9prady9** [comment]
build arrayfire windows cuda ci

**Comment by 9prady9** [comment]
@pavanky Tests added. 

This is ready for merge.

File: src/backend/cuda/kernel/morph.hpp [hunk 1]
```diff
@@ -239,22 +237,30 @@ void morph(Param<T> out, CParam<T> in, int windLen)
...
+        case 11: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 11>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 12: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 12>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 13: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 13>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 14: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 14>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 15: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 15>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 16: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 16>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 17: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 17>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 18: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 18>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        case 19: CUDA_LAUNCH_SMEM((morphKernel<T, isDilation, 19>), blocks, threads, shrdSize, out, in, blk_x, blk_y); break;
+        default: CUDA_NOT_SUPPORTED(); break;
```
Comment (umar456) [inline src/backend/cuda/kernel/morph.hpp]: We should document this limitation in doxygen. Also we should modify the CUDA_NOT_SUPPORTED function to say what is not supported.

Comment (umar456) [reply src/backend/cuda/kernel/morph.hpp]: it would be better if we had a generic kernel which handled the cases we cannot address with template parameters.

File: src/backend/opencl/morph3d_impl.hpp [hunk 2]
```diff
@@ -18,31 +18,32 @@ using af::dim4;
...
 {
-
 template<typename T, bool isDilation>
 Array<T> morph3d(const Array<T> &in, const Array<T> &mask)
 {
     const dim4 mdims    = mask.dims();
 
     if (mdims[0]!=mdims[1] || mdims[0]!=mdims[2])
-        AF_ERROR("Only cube masks are supported in opencl morph currently", AF_ERR_SIZE);
+        OPENCL_NOT_SUPPORTED("Only cube masks are supported in opencl morph currently");
```
Comment (umar456) [inline src/backend/opencl/morph3d_impl.hpp]: It looks like we don't support this functionality in CUDA or OpenCL. No need to specify that a certain backend doesn't support this. Also it would be better if you reworded it to:

"Cube masks are not supported."

File: src/backend/opencl/morph3d_impl.hpp [hunk 3]
```diff
@@ -18,31 +18,32 @@ using af::dim4;
...
+
     if (mdims[0]>7)
-        AF_ERROR("Upto 7x7x7 kernels are only supported in opencl currently", AF_ERR_SIZE);
+        OPENCL_NOT_SUPPORTED("Upto 7x7x7 kernels are only supported in opencl currently");
```
Comment (umar456) [inline src/backend/opencl/morph3d_impl.hpp]: "Kernels larger than 7x7x7 are not supported."

File: src/backend/opencl/kernel/morph.cl [hunk 4]
```diff
@@ -33,12 +33,14 @@ void morph(__global T *              out,
...
            __constant const T *   d_filt,
            __local T *          localMem,
-           int nBBS0, int nBBS1)
+           int nBBS0, int nBBS1, int windLen)
 {
-    const int halo   = windLen/2;
-    const int padding= 2*halo;
-    const int shrdLen = get_local_size(0) + padding + 1;
-    const int shrdLen1= get_local_size(1) + padding;
+    windLen = (SeLength>0 ? SeLength : windLen);
```
Comment (umar456) [inline src/backend/opencl/kernel/morph.cl]: ternary operator causes a lot of problems with some compilers. Can you make this an if statement?

File: src/backend/cuda/morph_impl.hpp [hunk 5]
```diff
@@ -17,16 +17,16 @@ using af::dim4;
...
 {
-
 template<typename T, bool isDilation>
 Array<T>  morph(const Array<T> &in, const Array<T> &mask)
 {
     const dim4 mdims = mask.dims();
 
     if (mdims[0] != mdims[1])
-        AF_ERROR("Only square masks are supported in cuda morph currently", AF_ERR_SIZE);
+        CUDA_NOT_SUPPORTED("Only square masks are supported in cuda morph currently");
```
Comment (umar456) [inline src/backend/cuda/morph_impl.hpp]: "Rectangular masks are not supported"

File: src/backend/cuda/morph3d_impl.hpp [hunk 6]
```diff
@@ -17,17 +17,16 @@ using af::dim4;
...
 {
     const dim4 mdims = mask.dims();
 
     if (mdims[0] != mdims[1] || mdims[0] != mdims[2])
-        AF_ERROR("Only cube masks are supported in CUDA backend", AF_ERR_SIZE);
+        CUDA_NOT_SUPPORTED("Only cube masks are supported in CUDA backend");
 
     if (mdims[0] > 7)
-        AF_ERROR("Upto 7x7x7 kernels are only supported in CUDA backend", AF_ERR_SIZE);
+        CUDA_NOT_SUPPORTED("Upto 7x7x7 kernels are only supported in CUDA backend");
```
Comment (umar456) [inline src/backend/cuda/morph3d_impl.hpp]: "Kernels larger than 7x7x7 are not supported."

File: src/backend/cuda/kernel/morph.hpp [hunk 7]
```diff
@@ -59,17 +57,25 @@ inline __device__ void load2ShrdMem(T * shrd, const T * const in,
 
 // kernel assumes mask/filter is square and hence does the
 // necessary operations accordingly.
-template<typename T, bool isDilation, int windLen>
+// PLEASE MAKE SURE at least one of the following variables is not 0.
```
Comment (umar456) [inline src/backend/cuda/kernel/morph.hpp]: A note would be fine. It would be better if you could document the template and function args.

File: src/backend/opencl/morph_impl.hpp [hunk 8]
```diff
@@ -18,37 +18,36 @@ using af::dim4;
...
+        case  8: kernel::morph<T, isDilation,  8>(out, in, mask); break;
         case  9: kernel::morph<T, isDilation,  9>(out, in, mask); break;
-        case 11: kernel::morph<T, isDilation, 11>(out, in, mask); break;
-        case 13: kernel::morph<T, isDilation, 13>(out, in, mask); break;
-        case 15: kernel::morph<T, isDilation, 15>(out, in, mask); break;
-        case 17: kernel::morph<T, isDilation, 17>(out, in, mask); break;
-        case 19: kernel::morph<T, isDilation, 19>(out, in, mask); break;
-        default: kernel::morph<T, isDilation,  3>(out, in, mask); break;
+        case 10: kernel::morph<T, isDilation, 10>(out, in, mask); break;
+        default: kernel::morph<T, isDilation>(out, in, mask, mdims[0]); break;
```
Comment (umar456) [inline src/backend/opencl/morph_impl.hpp]: This kernel is not tested. Can you make a test case which exercises this kernel?

**Comment by 9prady9** [comment]
@umar456 This is ready for merge.
