### PR TITLE
Bug fixes and proper dimension error checks

### LINKED ISSUE #607: Arrays created with the default constructor have numdims of 4
The numdims function returns 4 for af::arrays which are created using the default constructor. It should return 0 because these arrays do not contain values.

```c++
array a;
cout << "# dims: " << a.numdims() << endl; //Prints 4
```

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #607

### CODE REVIEW

File: src/api/cpp/array.cpp [hunk 1]
```diff
@@ -252,11 +253,7 @@ namespace af
     array::~array()
     {
         af_array tmp = get();
-        if (tmp != 0){
-            if(AF_SUCCESS != af_destroy_array(tmp)) {
-                fprintf(stderr, "Error: Couldn't destroy af::array %p", this);
-            }
-        }
+        if (tmp) AF_THROW(af_destroy_array(tmp));
```
Comment (umar456) [inline src/api/cpp/array.cpp]: Destructor MUST never throw
