### PR TITLE
Windows specific fixes and segfault fix for graphics

### LINKED ISSUE #2440: Segmentation fault ForgeManager
Hi
When trying to run wav2letter's Train (to train WSJ), I get this error:
```
wav2letter/recipes/wsj$ ../../build/Train train -flagfile configs/conv_glu/train.cfg
*** Aborted at 1550243856 (unix time) try "date -d @1550243856" if you are using GNU date ***
PC: @     0x2b8d2a0f8328 graphics::ForgeManager::~ForgeManager()
*** SIGSEGV (@0x0) received by PID 104862 (TID 0x2b8d021fc4c0) from PID 0; stack trace: ***
    @     0x2b8d069fb0c0 (unknown)
    @     0x2b8d2a0f8328 graphics::ForgeManager::~ForgeManager()
    @     0x2b8d29b88760 std::default_delete<>::operator()()
    @     0x2b8d29b877e7 std::unique_ptr<>::~unique_ptr()
    @     0x2b8d29b83ca7 cuda::DeviceManager::DeviceManager()
    @     0x2b8d29b81bc5 cuda::DeviceManager::getInstance()
    @     0x2b8d29b81c86 cuda::memoryManager()
    @     0x2b8d29b5788e cuda::setMemStepSize()
    @     0x2b8d29e18614 af_set_mem_step_size
    @     0x2b8d2a08af72 af::setMemStepSize()
    @     0x561939f44e6e main
    @     0x2b8d6789f2e1 __libc_start_main
    @     0x561939f8512a _start
    @                0x0 (unknown)
Segmentation fault
```
I have compiled Arrayfire and wav2letter with cuda 9.2.
Could you please help with this issue? I have already asked this on wav2letter's github: https://github.com/facebookresearch/wav2letter/issues/208

And here is a backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00002aaad2a15328 in graphics::ForgeManager::~ForgeManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
(gdb) bt
#0  0x00002aaad2a15328 in graphics::ForgeManager::~ForgeManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#1  0x00002aaad24a5760 in std::default_delete<graphics::ForgeManager>::operator()(graphics::ForgeManager*) const ()
   from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#2  0x00002aaad24a47e7 in std::unique_ptr<graphics::ForgeManager, std::default_delete<graphics::ForgeManager> >::~unique_ptr() ()
   from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#3  0x00002aaad24a0ca7 in cuda::DeviceManager::DeviceManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#4  0x00002aaad249ebc5 in cuda::DeviceManager::getInstance() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#5  0x00002aaad249ec86 in cuda::memoryManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#6  0x00002aaad247488e in cuda::setMemStepSize(unsigned long) () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#7  0x00002aaad2735614 in af_set_mem_step_size () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#8  0x00002aaad29a7f72 in af::setMemStepSize(unsigned long) () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#9  0x0000555555585e6e in main ()
```

### PR DESCRIPTION
**Pull request by 9prady9**
Resolves #2440 

Also includes couple of windows specific fixes.

### CODE REVIEW

File: src/backend/common/graphics_common.cpp [hunk 1]
```diff
@@ -233,34 +233,36 @@ ForgeModule& forgePlugin() { return detail::forgeManager().plugin(); }
...
-        for (int i = 0; i < (int)(iter->second).size(); i++) {
-            fg_chart chrt = (iter->second)[i];
-            if (chrt) {
-                mChartAxesOverrideMap.erase((chrt));
-                mPlugin->fg_release_chart(chrt);
+    if (mPlugin->isLoaded()) {
+        /* clear all OpenGL resource objects (images, plots, histograms etc) first
+         * and then delete the windows */
+        for (ImgMapIter iter = mImgMap.begin(); iter != mImgMap.end(); iter++)
+            mPlugin->fg_release_image(iter->second);
```
Comment (umar456) [inline src/backend/common/graphics_common.cpp]: We should have this in a unique_ptr with a custom deleter. This is not the best approach to releasing resources.

File: src/backend/cuda/CMakeLists.txt [hunk 2]
```diff
@@ -530,7 +530,15 @@ if(AF_INSTALL_STANDALONE)
   afcu_collect_libs(cublas)
   afcu_collect_libs(cusolver)
   afcu_collect_libs(cusparse)
-  afcu_collect_libs(nvrtc)
+
+  if(WIN32 AND ${CUDA_VERSION_MAJOR} EQUAL 10 AND ${CUDA_VERSION_MINOR} EQUAL 0)
+    message("This worked!")
```
Comment (umar456) [inline src/backend/cuda/CMakeLists.txt]: Forgot to remove this message.

File: src/backend/common/graphics_common.cpp (hunk 1 above)
Comment (9prady9) [reply src/backend/common/graphics_common.cpp]: Agree, but lets do that in different PR. I want to do more changes in forgemanager related code now that I look into it. Please approve the fix to correct segfaults on master. I will send a different PR with my changes to forgemanager that will handle what you suggested also.
