### PR TITLE
Image IO 16-bit tests, Bug fixes

### LINKED ISSUE #995: opencl sort_by_key and sort_index failing intermittently
uncomment the following tests after the issues is fixed:
```
diff --git a/test/sort_by_key.cpp b/test/sort_by_key.cpp
index 4f817aa..35bbc97 100644
--- a/test/sort_by_key.cpp
+++ b/test/sort_by_key.cpp
@@ -115,9 +115,10 @@ void sortTest(string pTestFile, const bool dir, const unsigned resultIdx0, const
     SORT_INIT(Sort10x10True,  sort_by_key_2D,    true,  0, 1);
     SORT_INIT(Sort10x10False, sort_by_key_2D,    false, 2, 3);
     SORT_INIT(Sort1000True,   sort_by_key_1000,  true,  0, 1);
-    SORT_INIT(Sort1000False,  sort_by_key_1000,  false, 2, 3);
     SORT_INIT(SortMedTrue,    sort_by_key_med,   true,  0, 1);
-    SORT_INIT(SortMedFalse,   sort_by_key_med,   false, 2, 3);
+    // FIXME: below two tests are disabled temporarily until issue#995 is fixed
+    //SORT_INIT(Sort1000False,  sort_by_key_1000,  false, 2, 3);
+    //SORT_INIT(SortMedFalse,   sort_by_key_med,   false, 2, 3);
     // Takes too much time in current implementation. Enable when everything is parallel
     //SORT_INIT(SortLargeTrue,  sort_by_key_large, true,  0, 1);
     //SORT_INIT(SortLargeFalse, sort_by_key_large, false, 2, 3);
diff --git a/test/sort_index.cpp b/test/sort_index.cpp
index f429626..1f503a7 100644
--- a/test/sort_index.cpp
+++ b/test/sort_index.cpp
@@ -116,9 +116,10 @@ void sortTest(string pTestFile, const bool dir, const unsigned resultIdx0, const
     SORT_INIT(Sort10x10True,  sort_10x10, true,  0, 1);
     SORT_INIT(Sort10x10False, sort_10x10, false, 2, 3);
     SORT_INIT(Sort1000True,   sort_1000,  true,  0, 1);
-    SORT_INIT(Sort1000False,  sort_1000,  false, 2, 3);
     SORT_INIT(SortMedTrue,    sort_med1,  true,  0, 1);
-    SORT_INIT(SortMedFalse,   sort_med1,  false, 2, 3);
+    // FIXME: below two tests are disabled temporarily until issue#995 is fixed
+    //SORT_INIT(Sort1000False,  sort_1000,  false, 2, 3);
+    //SORT_INIT(SortMedFalse,   sort_med1,  false, 2, 3);
     // Takes too much time in current implementation. Enable when everything is parallel
     //SORT_INIT(SortMed5True,   sort_med,   true,  0, 1);
     //SORT_INIT(SortMed5False,  sort_med,   false, 2, 3);

```

### LINKED ISSUE #1004: CUDA backend activates all available GPUs
Currently the CUDA backend activates all available GPUs in `DeviceManager`.

This is a problem in a host with multiple GPUs and where the GPUs are set to Thread or Process Exclusive. If you have two users trying to run arrayfire code, the second one will not find any available GPUs, even though the first user is probably just using one GPU.

Is there a way to tell arrayfire not to be greedy and only take one of the GPUs?

### LINKED ISSUE #1227: Add tests for 16bpc/48bpp images in ImageIO
* Use 16-bit/48bpp PNG Images to tests
* Load using both loadImageNative and loadImage (and save image)
* Add 8-bit image tests for Native functions

### LINKED ISSUE #1228: Bugs in ImageIO
* Fix handling 16-bpc images in saveImage
* Fix offset for grayscale images in saveImageNative

### LINKED ISSUE #1230: Use single memory struct vector for CUDA Pinned Memory Manager
CUDA Pinned memory manager is device independent. Use a single vector instead of n-devices.

### PR DESCRIPTION
**Pull request by shehzan10**
db14451 Fixes #995 
968ae4e and #1202  Fixes #1004 
88cf471 Fixes #1227 
b14ae20 and 6da71e5 Fixes #1228 
3eebcd9 fixes #1230

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire ci

File: src/api/c/imageio.cpp [hunk 1]
```diff
@@ -299,9 +299,16 @@ af_err af_save_image(const char* filename, const af_array in_)
             AF_CHECK(af_mul(&in, in_, c255, false));
             AF_CHECK(af_release_array(c255));
             free_in = true;
-        } else {
+        } else if(max_real < 256) {
             in = in_;
         }
+        else if (max_real < 65536) {
```
Comment (pavanky) [inline src/api/c/imageio.cpp]: `} else` should be one line

Comment (shehzan10) [inline src/api/c/imageio.cpp]: Resolved
