### PR TITLE
Use compute for nvrtc based on CUDA toolkit version

### LINKED ISSUE #2471: Titan RTX Cuda backend crashing
When running benchmarks/blas_cuda I get
```
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 6da99359)
Platform: CUDA Toolkit 10.0, Driver: 418.43
[0] TITAN RTX, 24191 MB, CUDA Compute 7.5
Benchmark N-by-N matrix multiply
ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR

In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af::matProp)
In file src/api/cpp/blas.cpp:18
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR

In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af::matProp)
In file src/api/cpp/blas.cpp:18
Aborted (core dumped)
```
I also tried the installer version. The Open CL backend also gives different results and sometimes crashes on my code (comparing against a quadro p2000 mobile). 

Running Linux 4.19.30-1

I checked issue #2343, CMake seems to have found the correct cuda compute (7.5, it is in the output above as well).

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #2471

### CODE REVIEW

File: src/backend/cuda/nvrtc/cache.cpp [hunk 1]
```diff
@@ -68,6 +74,7 @@ using kc_t = map<string, Kernel>;
         char* logptr = log.get();                      \
         nvrtcGetProgramLog(prog, logptr);              \
         logptr[logSize] = '\x0';                       \
+        printf("Compile error log: \n %s \n", logptr); \
```
Comment (WilliamTambellini) [inline src/backend/cuda/nvrtc/cache.cpp]: any way to print to stderr ?

Comment (9prady9) [reply src/backend/cuda/nvrtc/cache.cpp]: In fact, we will remove this soon once we add logging to nvrtc compilation pipeline. At which point, it would would use `AF_JIT_KERNEL_TRACE` environment variable I think.

File: src/backend/cuda/nvrtc/cache.cpp [hunk 2]
```diff
@@ -89,6 +96,49 @@ void Kernel::setConstant(const char* name, CUdeviceptr src, size_t bytes) {
...
+        int cuda_version;
+
+        /// Maximum major compute flag supported by cuda_version
+        int major;
+
+        /// Maximum minor compute flag supported by cuda_version
+        int minor;
+    };
+    static const cuNVRTCcompute Toolkit2Compute[] = {
+        {10010, 7, 5},
```
Comment (umar456) [inline src/backend/cuda/nvrtc/cache.cpp]: I think you should convert the compute versions to int format on the right. There is not maximum minor version. For example if the maximum version was 7.0, then the condition below will fail for version 5.3. You can use the https://github.com/arrayfire/arrayfire/blob/bce559f881006932de7c2a6787217dacc4c52937/src/backend/cuda/platform.cpp#L246 to convert it to string.

**Comment by 9prady9** [comment]
I still have to debug the `vision` function failures after this change. Not sure how what I changed is causing them to fail. Will push a fix soon.
