### PR TITLE
BUGIFX: Fixes issue with gemv when the rhs is an indexed vector

### LINKED ISSUE #1882: matmulTT(A,B) not same as matmul(transpose(A), transpose(B)) if B is submatrix
The result obtained by  **af::matmulTT(A, B)** is not same as the result obtained by **af::matmul(af::transpose(A), af::transpose(B))** if B is obtained as submatrix (B = BB(0, af::span))

```
// create matrix A
// [ 1.0 + 2.0i, 7.0 + 0.0i, 5.0 + 0.0i ]
// [ 2.0 + 3.0i, 2.0 + 0.0i, 3.2 + 0.0i ]
double A_realValues[] = { 1.0, 2.0, 7.0, 2.0, 5.0, 3.2 };
double A_imagValues[] = { 2.0, 3.0, 0.0, 0.0, 0.0, 0.0 };

af::array A_real(2, 3, A_realValues);
af::array A_imag(2, 3, A_imagValues);

af::array A = af::complex(A_real, A_imag);

// create matrix BB 
// [ 0.5, 0.5 ] 
// [ 0.0, 0.0 ]
// [ 0.0, 0.0 ]
double BB_realValues[] = { 0.5, 0.0, 0.0, 0.5, 0.0, 0.0 };
double BB_imagValues[] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };

af::array BB_real = af::array(3, 2, BB_realValues);
af::array BB_imag = af::array(3, 2, BB_imagValues);

af::array BB = af::complex(BB_real, BB_imag);

// own computation (compute average value across columns in A)
af::array B = BB(0, af::span); // B = [0.5 + 0.0i, 0.5 + 0.0i]

af::array result_ok = af::transpose(af::matmul(af::transpose(A), af::transpose(B)));
af::array result_wrong = af::transpose(af::matmulTT(A, B));
	
// result_ok
// [1 3 1 1]
// (1.5000, 2.5000) (4.5000, 0.0000) (4.1000, 0.0000)
af_print(result_ok);

// result_wrong
//	[1 3 1 1]
// (0.5000, 1.0000)(3.5000, 0.0000)(2.5000, 0.0000)
af_print(result_wrong);
```

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1882

### CODE REVIEW

File: test/blas.cpp [hunk 1]
```diff
@@ -245,3 +245,23 @@ TYPED_TEST(MatrixMultiply, MultiGPURectangleVector_CPP)
...
+
+    af::array res1 = af::matmul(A.T(), B.T());
+    af::array res2 = af::matmulTT(A, B);
+
+    std::vector<float> hres1(res1.elements());
+    std::vector<float> hres2(res2.elements());
+    ASSERT_EQ(hres1.size(), hres2.size());
+
+    for (size_t i = 0; i < hres1.size(); i++) {
+        ASSERT_EQ(hres1[i], hres2[i]);
```
Comment (FloopCZ) [inline test/blas.cpp]: I believe that `hres1` and `hres2` are just vectors full of zeros, since no data were copied into them. So this assert will always be true.

Comment (pavanky) [inline test/blas.cpp]: Aww sorry. Forgot to call host.
