### PR TITLE
Fix in gfor tutorial

### LINKED ISSUE #2681: error in gfor documentation
In the introduction of the [gfor documentation](http://arrayfire.org/docs/page_gfor.htm), the 3 prototypes of `gfor` are explained:
```
1. gfor(var,n) Creates a sequence _{0, 1, ..., n-1}_
2. gfor(var,first,last) Creates a sequence _{first, first+1, ..., last}_
3. gfor(var,first,incr,last) Creates a sequence _{first, first+inc, first+2*inc, ..., last}_
```
The third one is not "gfor(var,first,incr,last)" but "gfor(var,first,**last,incr**)", as the parameters are directly forwarded to the `seq` constructor [here](https://github.com/arrayfire/arrayfire/blob/4b450a7aac2c1a70dd90494ea4ebc878f2665095/include/af/gfor.h#L26).

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #2681

### CODE REVIEW

File: test/gfor.cpp [hunk 1]
```diff
@@ -499,3 +499,25 @@ TEST(ASSIGN, ISSUE_1127) {
...
+    const int start = 0;
+    const int end   = 8;
+    const int incr  = 2;
+
+    array A = randu(nx, ny, batch);
+    array B = randu(nx, ny);
+    array C = constant(0, nx, ny, batch);
+    array G = constant(0, nx, ny, batch);
+
+    for (int i = 0; i < batch; i += 2) {
```
Comment (syurkevi) [inline test/gfor.cpp:516]: i += incr?
